language: go

go:
  - 1.5

dist: trusty

before_script:
  - wget http://tarantool.org/dist/1.6/tarantool-1.6.8.545.tar.gz -O /tmp/tarantool.tar.gz
  - cd /tmp
  - tar -xvf tarantool.tar.gz
  - cd /tmp/tarantool-1.6.8.545 && export PATH=$PATH:$PWD/src
  - cmake . && make

script:
  - cd $HOME/gopath/src/github.com/alexeyknyshev/android_cash_points/server
  - export GOPATH=$PWD
  - cd tnt_workdir && tarantool init.lua &
  - cd $GOPATH
  - go get github.com/alexeyknyshev/gojsondiff
  - go get github.com/alexeyknyshev/cpsrv
  - go build github.com/alexeyknyshev/cpsrv
  - echo "box.schema.user.passwd('admin', 'admin')" | nc localhost 3302
  - go test github.com/alexeyknyshev/cpsrv

#before_install:
#  - curl http://download.tarantool.org/tarantool/1.6/gpgkey | sudo apt-key add -
#  - sudo echo "deb http://download.tarantool.org/tarantool/1.6/ubuntu/ $(lsb_release -c -s) main" > /etc/apt/sources.list.d/tarantool_1_6.list
#  - sudo echo "deb-src http://download.tarantool.org/tarantool/1.6/ubuntu/ $(lsb_release -c -s) main" >> /etc/apt/sources.list.d/tarantool_1_6.list
#  - sudo apt-get update
#  - sudo sudo apt-get -y install tarantool
